"use client";
import { useMemo, useState } from "react";

type Player={name:string;gender:"Fille"|"Garçon"}; type Kind="Action"|"Vérité";
const packs={
  "Entre amis":{Action:["Fais une imitation de quelqu’un du groupe jusqu’à ce qu’on devine.","Laisse le groupe choisir une chanson : danse dessus pendant 20 secondes.","Fais le compliment le plus original à la personne à ta droite.","Parle avec un accent choisi par le groupe pour les deux prochains tours."],Vérité:["Quel est ton plus grand talent inutile ?","Quelle est la chose la plus drôle qui te soit arrivée cette année ?","Si tu pouvais échanger ta vie avec quelqu’un ici pendant une journée, qui choisirais-tu ?","Quel est le dernier mensonge innocent que tu as dit ?"]},
  "Flirt":{Action:["Fais un compliment sincère à une personne de ton choix.","Regarde une personne dans les yeux pendant dix secondes sans rire.","Envoie un emoji qui décrit ton mood à quelqu’un du groupe.","Choisis une personne et invente votre nom de duo."],Vérité:["Quelle qualité te fait craquer chez quelqu’un ?","Quel est le plus beau compliment que tu aies reçu ?","Quel serait ton rendez-vous parfait ?","Qu’est-ce qui te met immédiatement de bonne humeur ?"]},
  "Couple":{Action:["Rejouez ensemble votre premier rendez-vous en trente secondes.","Fais un massage des épaules de trente secondes à ton partenaire.","Dis trois choses que tu apprécies chez l’autre.","Choisissez une chanson qui vous représente et chantez le refrain."],Vérité:["Quel souvenir de nous te fait le plus sourire ?","Qu’aimerais-tu refaire ensemble bientôt ?","Quelle petite habitude de l’autre te fait fondre ?","Quel voyage rêverais-tu de faire à deux ?"]}
};
export default function Home(){
 const [players,setPlayers]=useState<Player[]>([{name:"Lina",gender:"Fille"},{name:"Alex",gender:"Garçon"},{name:"Maya",gender:"Fille"},{name:"Sam",gender:"Garçon"}]); const [name,setName]=useState("");const [gender,setGender]=useState<Player["gender"]>("Fille");const [pack,setPack]=useState<keyof typeof packs>("Entre amis");const [player,setPlayer]=useState<Player|null>(players[0]);const [kind,setKind]=useState<Kind>("Vérité");const [index,setIndex]=useState(0);const [spinning,setSpinning]=useState(false);
 const question=useMemo(()=>packs[pack][kind][index%packs[pack][kind].length],[pack,kind,index]);
 function spin(){if(spinning||!players.length)return;setSpinning(true);window.setTimeout(()=>{setPlayer(players[Math.floor(Math.random()*players.length)]);setKind(Math.random()>.5?"Action":"Vérité");setIndex((n)=>n+1);setSpinning(false)},1050)}
 function add(e:React.FormEvent){e.preventDefault();const clean=name.trim();if(clean&&!players.some(p=>p.name===clean)){const p={name:clean,gender};setPlayers([...players,p]);setPlayer(p)}setName("")}
 return <main className="app"><section className="game-shell"><div className="top"><div className="logo">ACTION <span>ou</span> VÉRITÉ</div><button className="help">?</button></div><div className="pack-tabs">{Object.keys(packs).map(p=><button key={p} onClick={()=>{setPack(p as keyof typeof packs);setIndex(0)}} className={pack===p?"on":""}>{p}</button>)}</div>
 <div className="playground"><div className="confetti c1">✦</div><div className="confetti c2">●</div><div className="confetti c3">✚</div><p className="turn">AU TOUR DE <b>{player?.name||"…"}</b></p><div className={`bottle ${spinning?"spin":""}`}><img src="/assets/spin-bottle.png" alt="Bouteille"/></div><button className="spin-button" onClick={spin} disabled={spinning}>{spinning?"ÇA TOURNE…":"FAIS TOURNER"}<span>↻</span></button></div>
 <div className="challenge"><div className="challenge-tabs"><button className={kind==="Action"?"active action":""} onClick={()=>setKind("Action")}>⚡ Action</button><button className={kind==="Vérité"?"active truth":""} onClick={()=>setKind("Vérité")}>✦ Vérité</button></div><div className={`card ${kind.toLowerCase()}`}><div className="card-label">{kind==="Action"?"DÉFI À RELEVER":"QUESTION À RÉPONDRE"}</div><p>{question}</p><div className="card-bottom"><button onClick={()=>setIndex(n=>n+1)}>Passer ↻</button><span>Sans pression, jamais obligé.</span></div></div></div>
 <section className="players"><div className="players-title"><b>JOUEURS</b><span>{players.length} dans la partie</span></div><div className="player-chips">{players.map(p=><div key={p.name} className={player?.name===p.name?"picked":""}><i className={p.gender==="Fille"?"pink":"blue"}>{p.name[0]}</i>{p.name}<button aria-label={`Retirer ${p.name}`} onClick={()=>{setPlayers(players.filter(x=>x.name!==p.name));if(player?.name===p.name)setPlayer(null)}}>×</button></div>)}</div><form onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ajouter un joueur"/><div className="gender-choice"><button type="button" className={gender==="Fille"?"chosen":""} onClick={()=>setGender("Fille")}>Fille</button><button type="button" className={gender==="Garçon"?"chosen":""} onClick={()=>setGender("Garçon")}>Garçon</button></div><button className="add" aria-label="Ajouter">+</button></form><small>Cette option sert uniquement à mieux adapter certaines cartes.</small></section></section></main>
}
